CC=gcc 
CFLAGS=-std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra

all: power struct_fun swap

power: power.c
struct_fun: struct_fun.c
swap: swap.c

clean:
	rm -f power
	rm -f struct_fun
	rm -f swap
