CC=gcc 
CFLAGS=-std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra

all: args arr_ptr arrays basics bits boolean do_while expr hello limits odd pointers sizeof strings structs switch tree tree_v2 typedef unions upper variants

args: args.c
arr_ptr: arr_ptr.c
arrays: arrays.c
basics: basics.c
bits: bits.c
boolean: boolean.c
do_while: do_while.c
expr: expr.c
hello: hello.c
limits: limits.c
odd: odd.c
pointers: pointers.c
sizeof: sizeof.c
strings: strings.c
structs: structs.c
switch: switch.c
tree: tree.c
tree_v2: tree_v2.c
typedef: typedef.c
unions: unions.c
upper: upper.c
variants: variants.c

clean:
	rm -f args
	rm -f arr_ptr
	rm -f arrays
	rm -f basics
	rm -f bits
	rm -f boolean
	rm -f do_while
	rm -f expr
	rm -f hello
	rm -f limits
	rm -f odd
	rm -f pointers
	rm -f sizeof
	rm -f strings
	rm -f structs
	rm -f switch
	rm -f tree
	rm -f tree_v2
	rm -f typedef
	rm -f unions
	rm -f upper
	rm -f variants
