all: args arr_ptr arrays basics expr hello odd sizeof strings structs switch typedef 

args: args.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o args args.c

arr_ptr: arr_ptr.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o arr_ptr arr_ptr.c

arrays: arrays.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o arrays arrays.c

basics: basics.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o basics basics.c

expr: expr.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o expr expr.c

hello: hello.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o hello hello.c

odd: odd.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o odd odd.c

sizeof: sizeof.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o sizeof sizeof.c

strings: strings.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o strings strings.c

structs: structs.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o structs structs.c

switch: switch.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o switch switch.c

typedef: typedef.c
	gcc -std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra -o typedef typedef.c

clean:
	rm -f args
	rm -f arr_ptr
	rm -f arrays
	rm -f basics
	rm -f expr
	rm -f hello
	rm -f odd
	rm -f sizeof
	rm -f strings
	rm -f structs
	rm -f switch
	rm -f typedef

